### PR TITLE
feat: implementation of IPLD format for Zcash

### PR DESCRIPTION
**Pull request by vmx**
This implementation is heavily based on js-ipld-bitcoin.

The Zcash fork of bitcoinjs-lib wasn't used as it couldn't
correctly serialize the deserialized Zcash block.

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Seems to be a lot of changes that is just changing the naming of the variables, which means we have a lot of duplicated logic between these two modules (js-ipld-bitcoin and js-ipld-zcash). Would it be possible to expose some interface from js-ipld-bitcoin that js-ipld-zcash could use instead? And this module would just have the difference, rather than all code duplicated.

**Comment by VictorBjelkholm** [comment]
Just a FYI: when setting up a new repository, please add the `ci` team with Write permissions so @ImmutableJenkins can write the commit status in PRs.

**Comment by vmx** [comment]
@VictorBjelkholm I thought about having common code between the Bitcoin and the Zcash implementation. But then I decided against it. Although they both share a lot of code, the total amount is pretty small and it's very easy to understand. Adding an abstraction would make the code harder to understand. My goal is to have easy to understand and maintain code.

**Comment by VictorBjelkholm** [comment]
@vmx understandable, but even if the amount is small, it is in fact duplicated in two repository. So if your goal is to have it easy to maintain, having two almost identical (I count two real changes, not counting renaming variables) code bases where patches most certainly have to be applied to both is increasing the maintenance burden, not decreasing it. 

Spitballing, but what about just having one codebase for both + future cryptocurrencies? Code reuse and maintenance becomes a lot simpler and it'll still be easy to understand.

**Comment by vmx** [comment]
@VictorBjelkholm: let me try to make it a single repository and see if I can make it work nicely. I'll update the issue once done.

PS: Just another note. There's even huge overlap between https://github.com/ipld/js-ipld-dag-cbor and https://github.com/ipld/js-ipld-dag-cbor (do a diff of their `src` directory). Though I wouldn't want to combine them.

**Comment by vmx** [comment]
@VictorBjelkholm Having things abstracted (not the single repo aproach I mention above) would probably make it look something like the resolver factory of js-ipld-ethereum (https://github.com/ipld/js-ipld-ethereum/blob/master/eth-block/index.js). Now that I've coded the Bitcoin implementation I can finally understand what they are doing. But when I first looked at the code, I had no clue what was going on. This is exactly what I try to prevent. I want easy to understand, edit and copy&pastable code.

Getting the Zcash stuff working was really straight forward (once I found a lib that can en/decode it properly). I don't think it would have been that easy/fast with more abstractions.

**Comment by vmx** [comment]
@diasdavid I started working playing with js-ipfs yesterday and plan continue that today :)

**Pull request merged**
